# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-21 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='budget_app.Account')),
                ('account_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='budget_app.Account')),
                ('card_from', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='budget_app.Card')),
                ('card_to', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='budget_app.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='login_app.User')),
            ],
        ),
    ]
