# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_auto_20191022_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='t_type',
        ),
    ]
