# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_auto_20191023_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='budget_app.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='budget_app.Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_from',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='budget_app.Card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='budget_app.Card'),
        ),
    ]
